### ISSUE TITLE
iPython require to work

### ISSUE THREAD

**Issue by JorgeDDW** [BotDevGroup/marvin#4]
`ipython` its required to run.

Also to work properly it requires `ipython`  

> /usr/local/Cellar/ipython/6.5.0/libexec/lib/python3.7/site-packages/IPython/core/interactiveshell.py:763: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
>   warn("Attempting to work in a virtualenv. If you encounter problems, please "
> 

## Context

@warchiefx mention this is a bug because it doesn't require `ipython`

## Possible Fix

Add the `ipython` package on the `requirement.txt` 

## Steps to Reproduce

1. [Follow the guide](https://github.com/BotDevGroup/marvin/wiki/Installation)

**Comment by cameri** [comment]
Added ipython.
